### ISSUE TITLE
Gitignored files are rendered with bright color

### ISSUE THREAD

**Issue by caesarsol** [ilariaventurini/ohlala#1]
Hi! The color for git-ignored files is bright instead of dimmed:

<img width="192" alt="image" src="https://user-images.githubusercontent.com/1799710/95889011-29047680-0d82-11eb-8d3b-171bf0dcc1de.png">

I would change this value to something like this:

https://github.com/ilariaventurini/ohlala/blob/master/vscode/themes/ohlala-color-theme.json#L930
```
"gitDecoration.ignoredResourceForeground": "#ffffff33"
```
<img width="212" alt="image" src="https://user-images.githubusercontent.com/1799710/95889123-50f3da00-0d82-11eb-8142-6b5e2a50f3f9.png">

:)

**Comment by ilariaventurini** [comment]
Hi! 
Solved using _gray-02_ (`#808182`) which is in the color palette with opacity 50%. Thanks!
